### ISSUE TITLE
Service_Working but with bug report

### ISSUE THREAD

**Issue by gekberlin** [aneeshd/schedule_state#155]
Hi,

if I call the service:
```
service: schedule_state.set_override
entity_id: sensor.heizungsplan_schreibtisch
data:
  id: Boost_Schreibtisch
  state: Boost
  duration: 60
  icon: mdi:calendar-star
  extra_attributes:
    zieltemperatur: 17C
```
the override "boost" is activated correctly to the shedule `sensor.heizungsplan_schreibtisch` but I do got some error messages in the log:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/schedule_state/sensor.py:294
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:26:32 (5 occurrences)
Last logged: 15:38:51

[139816548376384] Error handling message: Unknown error (unknown_error) Marius from 81.200.201.228 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76)
[139816656677440] Error handling message: Unknown error (unknown_error) Marius from 81.200.201.228 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 716, in handle_execute_script
    response = await script_obj.async_run(msg.get("variables"), context=context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/schedule_state/sensor.py", line 294, in async_remove_override_service_handler
    await asyncio.wait(update_tasks)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```
The same error is printed to the logs if i call the service:

```
service: schedule_state.remove_override
target: sensor.heizungsplan_schreibtisch
data:
  id: Boost_Schreibtisch
```

I do use Homeassistant core 2023.11.0 and schedule_state 0.18.1

Any help to slove this error would be appreciated.

**Comment by aneeshd** [comment]
since HomeAssistant 2023.9 or .10, some things have gotten broken. I am trying to fix...

**Comment by Reynders1** [comment]
> since HomeAssistant 2023.9 or .10, some things have gotten broken. I am trying to fix...

Hi @aneeshd ,
Any progress on this?
Christian

**Comment by aneeshd** [comment]
Unfortunately not. All of the unit tests are failing when I upgrade HA to 2023.11. It will take some time to find out what is happening.

**Comment by aneeshd** [comment]
If you are able to help fix, I have pushed my updates to the branch "upgrade-ha-and-fix-unittests"

**Comment by aneeshd** [comment]
@wdejaeghere thanks for that tip - that helped provide the fix

I also managed to fix the unit tests. New version has been published to HACS.

**Comment by Reynders1** [comment]
@aneeshd 
Perfectly working again! Many thanks!
