### ISSUE TITLE
AssertionError in logs in 0.18.0

### ISSUE THREAD

**Issue by eugenelitvinov** [aneeshd/schedule_state#92]
## Version of the schedule_state component

c8e39f2
## Configuration

```yaml

# Light scheduler
- platform: schedule_state
  name: Light schedule
  refresh: "6:00"
  default_state: day
  icon: mdi:calendar-check
  error_icon: mdi:calendar-alert
  minutes_to_refresh_on_error: 5
  extra_attributes:
    light_main: "off"
    light_subtle: "off"
    light_bedroom: "off"
    light_sensor: "full"
    light_default_brightness: "full"
  events:
    - state: day
      light_main: "off"
      light_subtle: "off"
      light_bedroom: "off"
      light_sensor: "full"
      light_default_brightness: "full"            
    - start: "15:00"
      condition:
        condition: or
        conditions:
          - condition: numeric_state
            entity_id: sun.sun
            value_template: "{{ state_attr('sun.sun', 'elevation') }}"
            below: 4.0
      state: evening
      light_main: "full"
      light_subtle: "full"
      light_bedroom: "full"
      light_sensor: "full"
      light_default_brightness: "full"
    - start: "22:00"
      state: wind_down
      condition:
        condition: or
        conditions:
          - condition: state
            entity_id: light.bedroom_bedside_lamps
            state: 'off'                 
      light_main: "off"
      light_subtle: "dim"
      light_bedroom: "off"
      light_sensor: "dim"
      light_default_brightness: "dim"  
    - start: "22:00"
      state: wind_down
      condition:
        condition: or
        conditions:
          - condition: state
            entity_id: light.bedroom_bedside_lamps
            state: 'on'           
      light_main: "dim"
      light_subtle: "dim"
      light_bedroom: "dim"
      light_sensor: "full"
      light_default_brightness: "full"
    - start: "23:30"
      state: night
      light_main: "off"
      light_subtle: "off"
      light_bedroom: "off"
      light_sensor: "dim"
      light_default_brightness: "dim"        
    - end: "06:00"
      state: night
      condition:
        condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
      light_main: "off"
      light_subtle: "off"
      light_bedroom: "off"
      light_sensor: "dim"
      light_default_brightness: "dim"                  
    - end: "07:00"
      state: night
      condition:
        condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'off'
      light_main: "off"
      light_subtle: "off"
      light_bedroom: "off"
      light_sensor: "dim"
      light_default_brightness: "dim"
    - start: "06:00"
      end: "08:00"
      state: morning
      condition:
        condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
      light_main: "off"
      light_subtle: "dim"
      light_bedroom: "off"
      light_sensor: "full"
      light_default_brightness: "full"                  
    - start: "07:00"
      end: "09:00"
      state: morning
      condition:
        condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'off'
      light_main: "off"
      light_subtle: "dim"
      light_bedroom: "off"
      light_sensor: "full"
      light_default_brightness: "full"             


```

## Describe the bug
Assertion Errors in Home Assistant logs since updating to the latest release.

## Debug log

```text

2023-03-13 21:47:12.339 INFO (MainThread) [custom_components.schedule_state.sensor] Light schedule:
{'day': [datetime.time(8, 0),datetime.time(15, 0)),
 'evening': [datetime.time(15, 0),datetime.time(22, 0)),
 'morning': [datetime.time(6, 0),datetime.time(8, 0)),
 'night': [datetime.time(0, 0),datetime.time(6, 0)) | [datetime.time(23, 30),datetime.time(23, 59, 59, 999999)),
 'wind_down': [datetime.time(22, 0),datetime.time(23, 30))}
{'light_bedroom': {Template("off"): [datetime.time(0, 0),datetime.time(15, 0)) | [datetime.time(23, 30),datetime.time(23, 59, 59, 999999)),
                   Template("full"): [datetime.time(15, 0),datetime.time(22, 0)),
                   Template("dim"): [datetime.time(22, 0),datetime.time(23, 30))},
 'light_default_brightness': {Template("full"): [datetime.time(8, 0),datetime.time(15, 0)),
                              Template("full"): [datetime.time(6, 0),datetime.time(8, 0)) | [datetime.time(15, 0),datetime.time(23, 30)),
                              Template("dim"): [datetime.time(0, 0),datetime.time(6, 0)) | [datetime.time(23, 30),datetime.time(23, 59, 59, 999999))},
 'light_main': {Template("off"): [datetime.time(0, 0),datetime.time(15, 0)) | [datetime.time(23, 30),datetime.time(23, 59, 59, 999999)),
                Template("full"): [datetime.time(15, 0),datetime.time(22, 0)),
                Template("dim"): [datetime.time(22, 0),datetime.time(23, 30))},
 'light_sensor': {Template("full"): [datetime.time(8, 0),datetime.time(15, 0)),
                  Template("full"): [datetime.time(6, 0),datetime.time(8, 0)) | [datetime.time(15, 0),datetime.time(23, 30)),
                  Template("dim"): [datetime.time(0, 0),datetime.time(6, 0)) | [datetime.time(23, 30),datetime.time(23, 59, 59, 999999))},
 'light_subtle': {Template("off"): [datetime.time(0, 0),datetime.time(6, 0)) | [datetime.time(8, 0),datetime.time(15, 0)) | [datetime.time(23, 30),datetime.time(23, 59, 59, 999999)),
                  Template("full"): [datetime.time(15, 0),datetime.time(22, 0)),
                  Template("dim"): [datetime.time(6, 0),datetime.time(8, 0)) | [datetime.time(22, 0),datetime.time(23, 30))}}
2023-03-13 21:47:12.339 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: current state is evening (21:47:00)
2023-03-13 21:47:12.339 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_main: full
2023-03-13 21:47:12.339 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_subtle: full
2023-03-13 21:47:12.340 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_bedroom: full
2023-03-13 21:47:12.340 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_sensor: full
2023-03-13 21:47:12.340 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_default_brightness: full
2023-03-13 21:47:33.449 DEBUG (MainThread) [custom_components.schedule_state.sensor] Heating schedule: current state is evening_occupied (21:47:00)
2023-03-13 21:47:33.449 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: current state is evening (21:47:00)
2023-03-13 21:47:33.449 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_main: full
2023-03-13 21:47:33.449 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_subtle: full
2023-03-13 21:47:33.449 DEBUG (MainThread) [custom_components.schedule_state.sensor] Light schedule: >> light_bedroom: full
2023-03-13 21:47:33.450 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.light_schedule fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/schedule_state/sensor.py", line 487, in async_update
    await self.data.update()
  File "/config/custom_components/schedule_state/sensor.py", line 979, in update
    attr_val, _ = self.find_interval(self._custom_attributes[attr], nu)
  File "/config/custom_components/schedule_state/sensor.py", line 1016, in find_interval
    assert False
AssertionError

```

**Comment by nagyrobi** [comment]
Any idea what could we do?

**Comment by aneeshd** [comment]
I will look at it this weekend. I’ve been busy at work. - aneeshSent from my iPhonePlease excuse any typos or logical fallacies. On Mar 24, 2023, at 17:03, H. Árkosi Róbert ***@***.***> wrote:﻿
Any idea what could we do?

**Comment by nagyrobi** [comment]
Let me know if any help is needed for testing etc.

**Comment by aneeshd** [comment]
I've managed to reproduce it in my pytest environment. Now to start debugging...

**Comment by aneeshd** [comment]
Please try 56461ac

**Comment by nagyrobi** [comment]
Thanks, testing...

**Comment by nagyrobi** [comment]
No more errors. Still testing.

**Comment by nagyrobi** [comment]
Still working fine since.

**Comment by nagyrobi** [comment]
Yes, thanks
